default_language_version:
  python: python3
default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Check for trailing whitespaces
      - id: check-yaml
        name: Check YAML files
      - id: detect-private-key
        name: Detect private keys
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Format code with Black
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.1
    hooks:
      - id: isort
        name: Sort imports with isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Lint code with flake8
        args:
          - --ignore=E501
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        name: my[py] static type check
        args:
          - --ignore-missing-imports
